- src/app/app.component.html
- src/app/app.module.ts
- src/app/components/login/login.component.html
- src/app/components/login/login.component.spec.ts
- src/app/components/login/login.component.ts
- src/app/components/register/register.component.html
- src/app/components/register/register.component.spec.ts
- src/app/components/register/register.component.ts
- src/app/core/app-routing.module.ts
- src/app/core/directives/alert/alert.component.html
- src/app/core/directives/alert/alert.component.ts
- src/app/core/guards/auth.guard.ts
- src/app/core/helpers/error.interceptor.ts
- src/app/core/helpers/fake-backend.ts
- src/app/core/helpers/index.ts
- src/app/core/helpers/jwt.interceptor.ts
- src/app/core/models/profile.ts
- src/app/core/models/user.ts
- src/app/core/services/alert/alert.service.spec.ts
- src/app/core/services/alert/alert.service.ts
- src/app/core/services/authentication/authentication.service.spec.ts
- src/app/core/services/authentication/authentication.service.ts
- src/app/core/services/book/book.service.ts
- src/app/core/services/user/user.service.spec.ts
- src/app/core/services/user/user.service.ts
Foram liberadas as rotinas para autentificação.
> Rotinas para Autentificação

- src/app/components/header/header.component.html
- src/app/components/header/header.component.ts
- src/app/core/services/authentication/authentication.service.ts
- src/app/core/services/user/user.service.ts
Mostrar usuário logado e opção de entrar/sair do sistema
> Mostrar usuário logado e opção de entrar/sair do sistema

- src/app/app-config.module.ts
- src/app/app.module.ts
- src/app/core/services/authentication/authentication.service.ts
- src/app/core/services/book/book.service.ts
- src/app/core/services/category/category.service.ts
- src/app/core/services/user/user.service.ts
Colocando em um arquivo de configuração o endpoint da API
> Colocar em um arquivo de config a URL da API

- src/app/components/login/login.component.ts
- src/app/components/register/register.component.html
- src/app/components/register/register.component.ts
- src/app/core/services/authentication/authentication.service.ts
- src/app/core/services/user/user.service.ts
Ajusta o login e o registro, já com o response da api.
Registra o usuário.
Efetua o login.
Já realiza as devidas validações
> Ajustar retornos na chamada a API - Login e Registro

- src/app/components/book/form/form.component.ts
- src/app/components/book/list/list.component.css
- src/app/components/book/list/list.component.html
- src/app/components/book/list/list.component.ts
- src/app/components/header/header.component.html
- src/index.html
Finalização do formulario/tabela de books com DELETE e direcionamento para formulário de edição dos dados do livro!
Correções na validação do livro campo frete para adicionar corretamente
> Alterações para melhorias e correções.

- src/app/core/app-routing.module.ts
- src/index.html
Adicionada opção no menu de Meu Painel quando logado, onde tem um card para a listagem dos livros que será para administrador e também uma para alterar o perfil do usuário para todos. 
Também foi voltado o CSS do BootStrap 4.0.0 devido problemas no CSS.
> CSS 4.0.0 e Meu Painel

- src/app/components/login/login.component.css
- src/app/components/register/register.component.css
- src/app/components/register/register.component.html
- src/app/components/register/register.component.ts
Alterada propriedade de cep para postalCode e corrigido CSS para icones do FA
> Propriedade cep para postalCode e CSS do FA

- src/app/components/account/account.component.css
- src/app/components/account/account.component.html
- src/app/components/account/account.component.ts
- src/app/components/login/login.component.css
- src/app/components/register/register.component.css
- src/app/core/models/updateUserVM.ts
- src/app/core/models/user.ts
- src/app/core/services/user/user.service.ts
Liberado componente para atualizar dados do usuário e algumas pequenas melhorias de layout.
> Componente para atualizar dados do usuário

- src/app/components/account/account.component.ts
- src/app/components/book/form/form.component.ts
- src/app/components/header/header.component.ts
- src/app/core/services/user/user.service.ts
Alterado update de POST para PUT, devida alteração do tipo no BACKEND e também refatorado o método de localStorage.
> Alterado update de POST para PUT

- src/app/components/account/account.component.html
- src/app/components/account/account.component.ts
- src/app/components/panel/panel.component.css
- src/app/components/panel/panel.component.html
- src/app/components/panel/panel.component.ts
- src/app/components/register/register.component.html
- src/app/components/register/register.component.ts
- src/app/core/utils/app.const.ts
- src/app/core/utils/passwordValidation.ts
- Validações no formulário de Registro
- Replicada validações do register para o account component
- Alterado cards para padrão utilizado no apoie o projeto e adicionado permissão de visualização para administrador/usuario
> Validações / Segurança

- src/app/app.module.ts
- src/app/components/book/form/form.component.html
- src/app/components/book/form/form.component.ts
- src/app/components/book/list/list.component.ts
- src/app/core/app-routing.module.ts
- src/app/core/guards/auth.guard.admin.ts
- src/app/core/guards/auth.guard.user.ts
- src/app/core/services/book/book.service.ts
Listagem de livros para ADM
Delete, Update (Aprova e Desaprova o book)
Diversos detalhes de UI
> Finalização CRUD do Book

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/book/details/details.component.html
- src/app/components/book/details/details.component.ts
- src/app/components/book/form/form.component.html
- src/app/components/book/form/form.component.ts
- src/app/components/home/home.component.html
- src/app/core/app-routing.module.ts
- src/app/core/models/book.ts
- src/app/core/services/book/book.service.ts
> PR referente a issue #62

- src/app/core/services/book/book.service.ts
Até o smart table ter um componente de paginação melhor como esta em PR https://github.com/akveo/ng2-smart-table/pull/550 ou acharmos outra solução de tables que contenha paginação
> Solução temporária para obter os dados no gerenciar livros

- src/app/components/book/details/details.component.html
- src/app/components/book/details/details.component.ts
- src/app/core/services/book/book.service.ts
> Solução do issue #62

- src/app/components/book/form/form.component.ts
Somente conseguiremos testar a alteração com o PR aprovado e Deploy em DEV.
> Removido Required da imagem por apresentar problema no formulário em iPhone

- README.md
- src/app/components/quem-somos/quem-somos.component.html
eae galera! massa demais o projeto, mas qdo tava lendo, me incomodei com o 'eh' uahuah, então peguei pra arrumar isso. 
é noizz
> Fix ortografia (eh -> é) 

- src/app/components/home/home.component.html
Ao abrir a pagina em resolução 1080p, a imagem não esticava até o final
Adicionei também alt na imagem, para acessibilidade e SEO
> Alterando width da img para ficar ok inclusive em resolução 1080p

- src/app/components/header/header.component.html
- src/app/components/header/header.component.ts
corrigindo Bug da navegação, tive que sobrescrever o método do bootstrap, mas agora a navegação está ok.
> corrigindo bug da navegação, sobrescrevendo o metodo do bootstrap

- src/app/components/account/account.component.html
- src/app/components/account/account.component.ts
- src/app/components/book/form/form.component.html
- src/app/components/book/form/form.component.ts
- src/app/components/login/login.component.html
- src/app/components/login/login.component.ts
- src/app/components/register/register.component.html
- src/app/components/register/register.component.ts
- Alterado campos de 50 caracteres para 200 caracteres. (Book: title, author - User: name)
- Alterado campo de email para usar Pattern de email no Login
> [FRONTEND] Aumentar o limite de caracteres no titulo do livro

- src/app/core/utils/app.const.ts
> [UserRegister] Fix password length verification

- src/app/components/book/donate/donate.component.html
> Issue #100

- src/app/components/book/form/form.component.css
- src/app/components/book/form/form.component.html
> Fix Book Cover pixeling on some screen sizes

- src/app/components/book/form/form.component.css
> [BookCover] Fix styling on mobile devices

- package-lock.json
- package.json
- src/app/app.component.ts
- src/environments/environment.prod.ts
- src/environments/environment.stg.ts
- src/environments/environment.ts
The user is removed from localstorage when his token is expired, forcing to redo the login.
> Remove User from LocalStorage when Token Expired

- src/app/components/book/donations/donations.component.ts
- src/app/components/book/list/list.component.css
> Nome da coluna no minhas doações, FIX css paginação do gerenciar livros

- src/app/components/account/account.component.css
- src/app/components/account/account.component.html
- src/app/components/account/account.component.ts
- src/app/components/book/details/details.component.ts
- src/app/components/book/request/request.component.html
- src/app/components/book/request/request.component.ts
- src/app/core/models/book.ts
1. Adicionado botão para buscar CEP na interface de Account afim de deixar a interface mais intuitiva para que já tem cadastro, mas ainda não tem endereço cadastrado.
2. Confirmação de endereço no momento de demonstrar interesse no livro
> Confirmação de endereço no momento de demonstrar interesse no livro

- src/app/components/home/home.component.html
Criação de simples HTML para apresentação do Autor Destaque conforme solicitado por **Raffaelo** na data de 24 de outubro.
Imagens e textos de apresentação fixas para composição conforme pedido.
> Inclusão Autor Destaque na home - solicitado

- src/app/components/login/login.component.html
> Escondendo link de resetar senha

- src/app/components/account/account.component.ts
- src/app/components/book/details/details.component.html
- src/app/components/book/details/details.component.ts
- src/app/core/models/book.ts
- src/app/core/models/user.ts
- src/app/core/services/user/user.service.ts
- Adicionado local de origem e alerta sobre frete na tela de detalhes do livro
- Ajustado alguns models da aplicação no frontend para refletir as alterações de models do backend
> Adicionado local de origem e alerta sobre frete na tela de detalhes do livro

- src/app/components/book/details/details.component.html
- src/app/components/book/details/details.component.spec.ts
- src/app/components/book/details/details.component.ts
- Corrigido BUG dos alertas de frete quando usuário não logado
- Adicionada quantidade de dias para escolha do livro
>  Corrigido BUG dos alertas de frete quando usuário não logado

- src/app/components/book/form/form.component.ts
- src/app/components/book/list/list.component.ts
- Nome do facilitador na listagem de livros
- Validação de Facilitador somente na edição do Admin
> Ajustes Facilitador

- src/app/components/quem-somos/quem-somos.component.html
- src/app/components/quem-somos/quem-somos.component.ts
- src/app/core/models/contributor.ts
- src/app/core/models/link.ts
- src/app/core/services/contributors/contributors.service.ts
1. Adicionando os Models Contributor e Link para tipar o retorno do metódo getContributors do serviço Contributors
2. Remoção do código html hard coded, para a utilização do serviço
> Adição de um serviço para exibir contribuidores do projeto

- src/app/components/book/requesteds/requesteds.component.ts
- src/app/core/services/book/book.service.ts
- Alterado para buscar todos os livros e requests, sendo limite de 9999.
Fixes #170
> Fixes Issue #170 

- src/app/components/book/list/list.component.ts
- src/app/core/router/custom-reuse-strategy.ts
- Mudado layout da lista, adicionado cores dependendo a situação da data
- Alterado ReuseStrategy para cachear somente o book/list
- Adicionado winner e corrigido a falta do id
> 30 - EU, ENQUANTO CUSSA FACILITADOR PRECISO DE MELHORIAS NA TELA DE GERENCIAR LIVROS PRA EU APOSENTAR A PLANILHA.

- package.json
- src/app/components/home/home.component.html
- src/index.html
- Removido componente do TAGGBOX que gera erro na página.
- Removido Teste Unitário no Push. O mesmo será implementado no CI posteriormente.
> Removido TAGGBOX e Teste Unitário no Push.

- src/app/components/account/account.component.html
- src/app/components/account/account.component.ts
- src/app/components/book/list/list.component.ts
- src/app/core/models/BookDonationStatus.ts
- src/app/core/services/book/book.service.ts
- Adicionado status CANCELED no ENUM
- Adicionado método cancelDonation para endpoint api/book/cancel/{id}
- Substituido eliminar livro pelo cancelar doação
> 29 - EU, ENQUANTO CUSSA FACILITADOR PRECISO INFORMAR QUE UMA DOAÇÃO FOI CANCELADA PARA QUE ESSA INFORMAÇÃO SEJA RASTREÁVEL.

- src/app/components/book/donations/donations.component.ts
- src/app/components/book/list/list.component.ts
- Alterado icones e adicionada validação para livros cancelados
- Adicionada Badge "danger" para livros cancelados na page de minhas doações
- Adicionado o ratreio no gerenciar livros
> Pequenas correções

- src/app/components/book/donate/donate.component.html
- src/app/components/book/donate/donate.component.ts
- src/app/components/book/donations/donations.component.ts
- src/app/core/services/book/book.service.ts
- SÓ PODE ESCOLHER NO DIA DA DECISÃO. ( ChooseDate )
- CASO TENHA 1 OU MAIS INTERESSADOS: MOSTRAR UMA LISTA COM APELIDOS E JUSTIFICATIVAS COM UM ÍCONE DE TROFÉU DO LADO.
- CASO O DOADOR NÃO GOSTE DOS INTERESSADOS, ELE DEVE TER A OPÇÃO DE RENOVAR A DOAÇÃO POR MAIS 10 DIAS.
- AO CLICAR NO TROFÉU DEVE ABRIR UM MODAL PRA INFORMAR JUSTIFICATIVA E CONFIRMAR.
Obs: o item abaixo não foi implementado pois foi mantido o que já tínhamos. Não necessita por hora também mostrar os dados em tela, pois são disparados e-mails.
- AO CONFIRMAR MOSTRAR OS DADOS PESSOAIS DO GANHADOR. SE POSSÍVEL COM UMA ANIMAÇÃO, COM FOGOS DE ARTIFÍCIO, ESTILO QUANDO VC GANHA UMA CORRIDA NO MÁRIO KART. :-D
> 28 - EU, ENQUANTO RODRIGO DOADOR, GOSTARIA DE SELECIONAR UM GANHADOR PRA COMPLETAR A DOAÇÃO.

- src/app/components/account/account.component.html
- src/app/components/account/account.component.ts
- src/app/components/register/register.component.html
- src/app/components/register/register.component.ts
> Issue #200: Usuário não consegue se cadastrar

- src/app/app.module.ts
- src/app/components/footer/footer.component.html
- src/app/components/privacy-policy/privacy-policy.component.html
- src/app/components/privacy-policy/privacy-policy.component.spec.ts
- src/app/components/privacy-policy/privacy-policy.component.ts
- src/app/core/app-routing.module.ts
Nosso app foi bloqueado no Google play, e precisamos com urgência de uma política de privacidade pra que o app volte a ser listado.
>  Política de privacidade.

- src/app/components/book/search-results/search-results.component.html
- src/app/components/book/search-results/search-results.component.ts
- src/app/core/services/book/book.service.ts
> Ajustes da PR #197

- src/app/components/home/home.component.html
- src/app/components/home/home.component.ts
- Caso não tenha livro, mostrar mensagem amigável. Alterado para chamar o endpoint do getRandomBooks somente se encontrar livros.
- Comentada a chamada do getRandomBooks, visto que esses livros não estão sendo mostrados na página
> Ajuste na home

- src/app/components/account/account.component.html
- src/app/components/contact-us/contact-us.component.html
- src/app/components/home/home.component.ts
- src/app/components/register/register.component.html
- Issue #219 
- Ajuste para mostrar mensagem somente após response do endpoint
> Issue #219

- .vscode/launch.json
- package-lock.json
- src/app/components/account/account.component.ts
- src/app/components/book/details/details.component.ts
- src/app/components/book/donate-page/donate-page.component.ts
- src/app/components/book/donate/donate.component.ts
- src/app/components/book/donations/donations.component.ts
- src/app/components/book/facilitator-notes/facilitator-notes.component.ts
- src/app/components/book/form/form.component.ts
- src/app/components/book/list/list.component.ts
- src/app/components/book/main-users/main-users.component.ts
- src/app/components/book/request/request.component.ts
- src/app/components/book/requesteds/requesteds.component.ts
- src/app/components/book/search-results/search-results.component.ts
- src/app/components/book/tracking/tracking.component.ts
- src/app/components/change-password/change-password.component.ts
- src/app/components/contact-us/contact-us.component.ts
- src/app/components/forgot-password/forgot-password.component.ts
- src/app/components/header/header.component.ts
- src/app/components/home/home.component.ts
- src/app/components/login/login.component.ts
- src/app/components/panel/panel.component.ts
- src/app/components/register/register.component.ts
- src/app/components/reset-password/reset-password.component.ts
Refatorado todos os subscribes dos componetes para serem desinscritos quando  o componente não são mais inecessários.
> Prevenção de vazamento de memória

- README.md
- src/app/components/input-search/input-search.component.html
- src/app/components/input-search/input-search.component.ts
Inclusões no Readme para alerta de problemas com Versões do Node e Angular.
> Incluindo Informações sobre Versão Node e Angular no Readme

- src/app/core/services/technologies/technologies.service.ts
Informações da versão atualizada do Angular e inclusão da versão do Ionic.
> Ajustes Descritivo

- src/app/app.component.html
- src/app/app.module.ts
- src/app/components/cookieconsent/cookieconsent.component.html
- src/app/components/cookieconsent/cookieconsent.component.scss
- src/app/components/cookieconsent/cookieconsent.component.spec.ts
- src/app/components/cookieconsent/cookieconsent.component.ts
> Cookie Consent

- .prettierrc
- src/app/components/book/requesteds/requesteds.component.ts
- src/app/core/models/BookRequestStatus.ts
Além disso fiz uma pequena configuração de prettier. Aumentei o limite horizontal de 80 para 120 caracteres.
Historicamente esse limite de 80 existe por conta dos computadores antigos da década de 80, em que realmente não cabiam mais de 80 caracteres por linha. 120 é bem conservador até. E fica bom de visualizar no github em que o limite eh um pouco maior que isso.
> Ajuste de enum no BookRequest.

- src/app/components/book/details/details.component.ts
Ajuste feito na página de detalhes do livro
https://sharebook.com.br/livros/
Campo: Quando será anunciado o ganhador desse livro?
> Ajuste no texto de 'Quando será anunciado ganhador'

- src/app/components/login/login.component.css
- src/app/components/login/login.component.html
- src/app/core/helpers/error.interceptor.ts
atualização do uso de métodos e módulos que estavam depreciados
>  ajuste para email minusculo na tela de login

- README.md
- src/app/components/cookieconsent/cookieconsent.component.scss
- src/app/components/login/login.component.html
1.  Adicionado 'cursor:pointer' nos botões do cookieconsent.component.html
2.  Substituindo 'Redefinir senha' por 'Esqueci minha senha' no login.
> Adicionado 'cursor:pointer' nos botões do cookieconsent.component.html

- angular.json
- src/app/components/book/list/list.component.html
- src/app/components/book/list/list.component.ts
Pessoal, esse é meio urgente porque os facilitadores pararam de aprovar livros e está acumulando. Hoje bateu 22 livros aguardando aprovação.
> Busca por status em gerenciar livros.

- src/app/core/services/technologies/technologies.service.ts
Update "TechnologiesService" from ".Net 5" to ".Net 6" at Backend
> Update "TechnologiesService" from ".Net 5" to ".Net 6" at Backend

- package-lock.json
- src/app/app.module.ts
- src/app/components/account/account.component.css
- src/app/components/account/account.component.html
- src/app/components/book/details/details.component.html
- src/app/components/book/donate-page/donate-page.component.html
- src/app/components/book/donations/donations.component.css
- src/app/components/book/donations/donations.component.html
- src/app/components/book/form/form.component.html
- src/app/components/book/list/list.component.css
- src/app/components/book/list/list.component.html
- src/app/components/book/request/request.component.html
- src/app/components/book/requesteds/requesteds.component.html
- src/app/components/change-password/change-password.component.html
- src/app/components/contact-us/contact-us.component.html
- src/app/components/forgot-password/forgot-password.component.html
- src/app/components/input-search/input-search.component.html
- src/app/components/input-search/input-search.module.ts
- src/app/components/login/login.component.html
- src/app/components/parent-aproval/parent-aproval.component.html
- src/app/components/register/register.component.html
- src/app/components/reset-password/reset-password.component.html
Substituição dos botões bootstrap para angular material
> Removendo btn bootstrap

- src/app/components/book/requesteds/requesteds.component.css
- src/app/components/book/requesteds/requesteds.component.html
- src/app/components/book/requesteds/requesteds.component.ts
- src/app/core/directives/confirmation-dialog/confirmation-dialog.component.html
- src/app/core/interfaces/IRequestResult.ts
- src/app/core/models/BookRequestStatus.ts
- src/app/core/services/book/book.service.ts
Adicionado a possibilidade de cancelar pedidos na página Meus Pedidos
> Funcionalidade de cancelamento de pedidos

- src/app/components/header/header.component.html
Menu não permanecida aberto quando usado no celular.
> Correção do menu em modo amburger

- package-lock.json
- src/app/components/home/home.component.css
- src/app/components/home/home.component.html
Fiz um ajuste solicitado pelo Raffaello, pois o título: 
Nenhum livro encontrado ☹
Ajude o Sharebook e doe um livro agora
Estava muito próximo do título:
Meetups em destaque
> ajuste de espaçamento no título: "Nenhum livro encontrado"

- src/app/components/card-meetup/card-meetup.component.css
Ajuste de visualização dos cards de meetups em telas de 375px e 360px
> ajuste de reponsividade

- package-lock.json
- src/app/components/card-meetup/card-meetup.component.css
- src/app/components/card-meetup/card-meetup.component.html
- src/app/components/home/home.component.css
- src/app/components/home/home.component.html
Ajuste no controle da responsividade dos cards de meetups
> Ajuste no card dos meetup

- src/app/components/card-meetup/card-meetup.component.html
Correção que retira a imagem fixa no card dos meetup
> Correção card meetup
